spring:
  data:
    redis:
      # Redis
      port: 6379
      # password:
      database: 0
      # 连接超时时间
      timeout: 10000ms
      lettuce:
        pool:
          # 最大连接数量，默认8
          max-active: 1024
          # 最大连接阻塞等待时间，默认-1ms
          max-wait: 10000ms
          # 最大空闲连接数，默认8
          max-idle: 200
          # 最小空闲连接数，默认0
          min-idle: 5

