server:
  port: 8081
#  ???????Cookie???????????????
  servlet:
    session:
      cookie:
        name: OAUTH2-CLIENT-SESSIONID01
#???????
oauth2-server-url: http://localhost:8080

security:
  oauth2:
    client:
#      ???????????????
      client-id: admin
      client-secret: 112233
      user-authorization-uri: ${oauth2-server-url}/oauth/authorize
      access-token-uri: ${oauth2-server-url}/oauth/token
    resource:
      jwt:
        key-uri: ${oauth2-server-url}/oauth/token_key

